import {readFileSync} from 'node:fs';
import {stripTypeScriptTypes} from 'node:module';
import vm from 'node:vm';
import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
let handler, rpcCalls=0, mode='valid';
const schedule=Object.fromEntries(['sun','mon','tue','wed','thu','fri','sat'].map(d=>[d,{enabled:true,open:'00:00',close:'00:00'}]));
const settings={is_open:true,pickup_enabled:true,delivery_enabled:true,weekly_schedule:schedule};
const client={auth:{getUser:async()=>({data:{user:null}})},rpc:async(name,args)=>{assert.equal(name,'create_guest_order_atomic');rpcCalls++;assert.equal(args.p_lines.length,1);assert.equal(args.p_order.total,mode==='delivery'?42:17);return{data:{order:{id:'test',total:args.p_order.total},duplicate:false}}},from(table){let single=false;const b={select(){return b},eq(){return b},in(){return b},order(){return b},single(){single=true;return b},maybeSingle(){single=true;return b},then(resolve,reject){let data;
 if(table==='orders')data=null;
 if(table==='branches')data={id:'branch',latitude:21,longitude:-101,business_settings:{...settings,is_open:mode!=='closed'}};
 if(table==='products')data=[{id:'product',name:'Taco',price:17,is_active:true,is_available:true}];
 if(table==='product_modifier_groups')data=[];
 if(table==='modifier_options')data=[{id:'foreign-option',name:'Ajeno',price_delta:1,is_available:true,modifier_group_id:'foreign'}];
 if(table==='delivery_zones')data=single?{id:'zone',fee:25,minimum_order:0,is_active:true,max_distance_km:5}:[{id:'zone',max_distance_km:5}];
 return Promise.resolve({data,error:null}).then(resolve,reject);}};return b}};
let code=readFileSync(new URL('../supabase/functions/create-guest-order/index.ts',import.meta.url),'utf8').replace(/^import .*;\n/gm,'');
code=stripTypeScriptTypes(code,{mode:'strip'});
vm.runInNewContext(code,{createClient:()=>client,Deno:{env:{get:()=> 'test-secret'},serve:f=>handler=f},crypto:webcrypto,TextEncoder,Response,Request,URL,console});
const base={requestId:'00000000-0000-4000-8000-000000000001',fulfillmentType:'pickup',paymentMethod:'cash',customer:{name:'Test',phone:'0000000000'},items:[{productId:'product',quantity:1}]};
async function run(name,body,status,m='valid'){mode=m;rpcCalls=0;const response=await handler(new Request('https://test.local',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));assert.equal(response.status,status,name+': '+await response.text());assert.equal(rpcCalls,status===201?1:0,name+' unexpected write');console.log('PASS',name)}
await run('valid pickup',base,201);
await run('fractional quantity',{...base,items:[{productId:'product',quantity:1.5}]},400);
await run('invalid request ID',{...base,requestId:'------------------------------------'},400);
await run('closed branch',base,409,'closed');
await run('foreign modifier',{...base,items:[{productId:'product',quantity:1,modifierOptionIds:['foreign-option']}]},400);
await run('repeated modifiers',{...base,items:[{productId:'product',quantity:1,modifierOptionIds:['foreign-option','foreign-option']}]},400);
const delivery={...base,fulfillmentType:'delivery',deliveryZoneId:'zone',address:{street:'Test',latitude:21,longitude:-101}};
await run('valid delivery',delivery,201,'delivery');
await run('missing location',{...delivery,address:{street:'Test'}},400);
await run('outside coverage',{...delivery,address:{street:'Test',latitude:25,longitude:-101}},409);
for(const day of Object.values(schedule))day.enabled=false;
await run('outside service schedule',base,409);
