create table if not exists public.order_tracking_links (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  token_hash text not null unique,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  revoked_at timestamptz
);

create index if not exists order_tracking_links_order_id_idx
  on public.order_tracking_links(order_id);
create index if not exists order_tracking_links_created_by_idx
  on public.order_tracking_links(created_by);

alter table public.order_tracking_links enable row level security;

comment on table public.order_tracking_links is
  'Secondary hashed tracking links generated by authorized staff for customer confirmations.';
